apiVersion: v1
kind: PersistentVolume
metadata:
  name: courses-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/courses-db-data"  # Adjust the path for each PostgreSQL instance

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: courses-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses-db
  template:
    metadata:
      labels:
        app: courses-db
    spec:
      containers:
        - image: lorenzogl/courses-db:GIT_SHA_SECRET
          imagePullPolicy: Always
          name: courses-db
          env:
            - name: ENV_VAR_1
              value: ENV_VAR_1_VALUE
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: TEST_ENV_VAR
              value: trigger-redeploy
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: courses-db-storage
      volumes:
        - name: courses-db-storage
          persistentVolumeClaim:
            claimName: courses-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: courses-db
spec:
  type: ClusterIP
  ports:
    - name: "courses-db"
      port: 5432
      targetPort: 5432
  selector:
    app: courses-db
