name: (DB) Publish Database Docker Image + Deploy to gke
on:
  push:
    paths:
      - '**.yml'
      - '**Dockerfile-db'
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}    # cluster name
  GKE_ZONE: us-central1-a               # cluster zone

jobs:
  publish-docker-image-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lorenzogl/courses-db
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ github.sha }}
          dockerfile: Dockerfile-db

  push-db-gke-pipeline:
    needs: publish-docker-image-database
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Create and populate kubernetes/courses-database.yml file
        env:
          MONGO_FULL_URL_SECRET: ${{ secrets.MONGO_URL }}
          GIT_SHA_SECRET: ${{ github.sha }}
        run: |
          touch kubernetes/courses-database.yml
          sed "s|MONGO_URL_PLACEHOLDER|$MONGO_FULL_URL_SECRET|" kubernetes-templates/courses-database.yml | sed "s|GIT_SHA_SECRET|$GIT_SHA_SECRET|" > kubernetes/courses-database.yml
          echo "cat kubernetes/courses-database.yml"
          cat kubernetes/courses-database.yml
        shell: bash

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Deploy
        run:
          kubectl apply -f ./kubernetes/courses-database.yml